language: generic
deploy:
  provider: s3
  access_key_id: AKIAJHS35VHMVM6FC4SA
  secret_access_key:
    secure: bIy6UnexsBAX15xZwZu8f1U2KNHpP9NRXiRq8pANiJIhrw9d0R3SCaBrzEOMcF3jnTvFO1tfh0kBG0C9gjT9TdHmUmcxS0BpsPxMSWy00+3nLkIFSIH8SFjlHsQ5TFdBFle4oijWUuOWlZUTHSx5QJ/Htmm8wu7ZuzcCdDsSgepJW85f5iHSd4HlewrORabwKuS4nJiRhLqVEvxwTsP3sKEaasK85k7A5vzLM14eV7M+Zc/PwBk/q1nYoGTGf6UThXdSQUgb6AVUot2S0wOg0hBJCX5iYzcBLomXr9qkTpWhCuQWxH/sRvFPmcNeDhdjD5hPBa9JW3K37JIC2JLn5uvTEOfFk52Ao1sgTXcOwt4YadFjkqVBSaMKJwBx5Ng8j52SlulIce1kPVi5aUyW4xiNatrH0cQMZcBndr+BwSOtnqB7O5ZA2D/DmY+LUUM1gNb3Pe2i5WlS9nuycwQ5HUAUIT75WxaOQBF2hWyFZoIxZIYBL37gepk33OiPC5262b7MTT/AE8JRjQXobuCDzM0rkZG1P++5rkauAHYaLD2lMPZoTfB80O4jR4oKGpqS5o4RW4Qzp8yGEyMpFqeGMmogtsQry7NvqP3HU4rPuSUuJnxLWr/pwKKYFDqFGsSwHSZRIk72souT39D2hx5b3HwFK9hW8zh2GpwRNDIxb+c=
  bucket: acc.cloudformation.build
  acl: bucket_owner_full_control
  on:
    repo: bitsmag/accSlDeployment
